# Generated by Django 3.1.4 on 2020-12-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_description_processor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
    ]
