# Generated by Django 3.1.4 on 2020-12-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_processor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Processor',
        ),
    ]
